version = "1.0"

[main]

services = [ "__APP__" ]

name.en = "Config panel"
name.fr = "Panneau de configuration"

help.en = "Configuration of your Loops server."
help.fr = "Configuration de votre serveur Loops."

    ################
    #### MAIL CONFIG
    ################

[main.mail]

name.en = "Email"
name.en = "Courriel"

help.en = "Email provider configuration."
help.fr = "Configuration du service d’envoi de courrier électronique."

    [main.mail.mail_mailer]
    ask.en = "Choose a mail provider"
    ask.fr = "Choisissez un service pour l’envoi des courriels"
    type = "select"
    choices.smtp = "SMTP"
    choices.mailgun = "Mailgun"
    choices.postmark = "Postmark"
    choices.resend = "Resend"

    [main.mail.smtp_host]
    ask.en = "SMTP Server Hostname"
    ask.fr = "Nom d'hôte du serveur SMTP"
    visible = "mailer == 'smtp'"
    bind = "MAIL_HOST:__INSTALL_DIR__/.env"
    default = "localhost"
    help.en = "The hostname of the SMTP server you want to use. Examples: mail.example.org, localhost"
    help.fr = "Le nom d'hôte du serveur SMTP que vous souhaitez utiliser. Exemples: mail.example.org, localhost"
    type = "string"

    [main.mail.smtp_port]
    ask.en = "SMTP Port"
    ask.fr = "Port SMTP"
    visible = "mailer == 'smtp'"
    bind = "MAIL_PORT:__INSTALL_DIR__/.env"
    help.en = "Port to use to connect to the SMTP server (usually 587, but could be 465 or 2525 depending on your provider)"
    help.fr = "Port à utiliser pour se connecter au serveur SMTP (habituellement 587, peut aussi être 465 ou 2525 en fonction du service)"
    type = "string"
    default = "587"

    [main.mail.smtp_username]
    ask.en = "SMTP Username"
    ask.fr = "Nom d'utilisateur SMTP"
    visible = "mailer == 'smtp'"
    bind = "MAIL_USERNAME:__INSTALL_DIR__/.env"
    help.en = "Username to use when authenticating with the SMTP server"
    help.fr = "Nom d'utilisateur à utiliser lors de l'authentification avec le serveur SMTP"
    type = "string"

    [main.mail.smtp_password]
    ask.en = "SMTP Password"
    ask.fr = "Mot de passe SMTP"
    visible = "mailer == 'smtp'"
    bind = "MAIL_PASSWORD:__INSTALL_DIR__/.env"
    help.en = "Password to use when authenticating with the SMTP server"
    help.fr = "Mot de passe à utiliser lors de l'authentification avec le serveur SMTP"
    type = "password"

    [main.mail.smtp_encryption]
    ask.en = "SMTP Encrytion"
    ask.fr = "Type de chiffrement"
    visible = "mailer == 'smtp'"
    bind = "MAIL_ENCRYPTION:__INSTALL_DIR__/.env"
    default = "localhost"
    help.en = "The hostname of the SMTP server you want to use. Examples: mail.example.org, localhost"
    help.fr = "Le nom d'hôte du serveur SMTP que vous souhaitez utiliser. Exemples: mail.example.org, localhost"
    type = "select"
    choices.tls = "TLS"
    choices.ssl = "SSL"

    [main.mail.smtp_from]
    ask.en = "SMTP From Address"
    ask.fr = "Adresse d'expédition SMTP"
    visible = "mailer == 'smtp'"
    bind = "MAIL_FROM_ADDRESS:__INSTALL_DIR__/.env"
    help.en = "From address for sent emails"
    help.fr = "L'adresse utilisée pour les e-mails envoyés"
    type = "email"
    example = "loops@__DOMAIN__"

    [main.mail.mailgun_domain]
    ask.en = "Mailgun domain"
    ask.fr = "Domaine Mailgun"
    visible = "mailer == 'mailgun'"
    bind = "MAILGUN_DOMAIN:__INSTALL_DIR__/.env"
    type = "string"

    [main.mail.mailgun_secret]
    ask.en = "Mailgun secret"
    ask.fr = "Clé secrète Mailgun"
    visible = "mailer == 'mailgun'"
    bind = "MAILGUN_SECRET:__INSTALL_DIR__/.env"
    type = "string"

    [main.mail.postmark_token]
    ask.en = "Postmark token"
    ask.fr = "Token Postmark"
    visible = "mailer == 'postmark'"
    bind = "POSTMARK_TOKEN:__INSTALL_DIR__/.env"
    type = "string"

    [main.mail.resend_key]
    ask.en = "Resend key"
    ask.fr = "Clé Resend"
    visible = "mailer == 'resend'"
    bind = "RESEND_KEY:__INSTALL_DIR__/.env"
    type = "string"
