#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/tests.v1.schema.json

test_format = 1.0

[default]


    # ------------
    # Tests to run
    # ------------
    
    # App is meant to be connected to the fediverse, so change_url is irrelevant
    exclude = ["change_url"]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.s3_key_id = "0123456789abcdef0123456789"
    args.s3_key_secret = "0123456789abcdef01234567890123456789abcdef0123456789"
    args.s3_bucket = "MySuperBucket"
    args.s3_path_style = true

    test_upgrade_from.1bc773e7c3bcb1419f45cb13959d983ddd801663.name = "1.0.0-beta.4y~ynh2
