#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/tests.v1.schema.json

test_format = 1.0

[default]


    # ------------
    # Tests to run
    # ------------
    
    # App is meant to be connected to the fediverse, so change_url is irrelevant
    exclude = ["change_url"]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.s3_key_id = "0123456789abcdef0123456789"
    args.s3_key_secret = "0123456789abcdef01234567890123456789abcdef0123456789"
    args.s3_bucket = "MySuperBucket"
    args.s3_path_style = true
    args.mail_mailer = "smtp"
    args.smtp_host = "smtp.example.com"
    args.smtp_port = "587"
    args.smtp_username = "camilledoe"
    args.smtp_password = "Abc1234!"
    args.smtp_encryption = "tls"
    args.smtp_from = "camilledoe@example.com"

    test_upgrade_from.21ac8e7006fb1ccc4f363aff583f2d2738edcb1b.name = "1.0.0-beta.3~ynh1"
